import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {googleIntegration} from '../lib/google.mjs';
test('Google imports are read-only, deduplicated, and recover from expired sync tokens',async()=>{
  const originalFetch=globalThis.fetch,old={...process.env};
  process.env.GOOGLE_CLIENT_ID='test-client';process.env.GOOGLE_CLIENT_SECRET='test-secret';process.env.GOOGLE_REDIRECT_URI='http://localhost:4313/api/google/callback';
  const db=new DatabaseSync(':memory:');let state={worlds:[{id:'w',name:'World'}],items:[]};const calls=[];let expired=false;
  globalThis.fetch=async(url,options={})=>{calls.push({url,method:options.method||'GET'});if(url.includes('/token'))return Response.json({access_token:'access',refresh_token:'refresh',expires_in:3600});if(url.includes('/revoke'))return new Response('');if(url.includes('calendarList'))return Response.json({items:[{id:'calendar',summary:'My calendar'}]});if(url.includes('/events?')){if(expired&&url.includes('syncToken=')){expired=false;return Response.json({error:'expired'},{status:410})}return Response.json({items:[{id:'event-1',summary:'External meeting',start:{dateTime:'2026-10-01T10:00:00Z'},end:{dateTime:'2026-10-01T11:00:00Z'},created:'2026-09-20T00:00:00Z',htmlLink:'https://calendar.google.com'}],nextSyncToken:'next-token'});}throw Error('Unexpected URL '+url);};
  try{const integration=await googleIntegration(db,()=>structuredClone(state),s=>state=s);const {url}=await integration.auth('session');const auth=new URL(url);assert.equal(auth.searchParams.get('scope'),'https://www.googleapis.com/auth/calendar.readonly');await integration.callback('code',auth.searchParams.get('state'),'session');assert.equal((await integration.calendars())[0].id,'calendar');await integration.sync([{id:'calendar',world:'w'}]);await integration.sync([{id:'calendar',world:'w'}]);assert.equal(state.items.length,1);assert.equal(state.items[0].external.provider,'Google Calendar');state.items.push({...state.items[0],id:'stale',external:{...state.items[0].external,event:'gone'}});expired=true;await integration.sync([{id:'calendar',world:'w'}]);assert.equal(state.items.length,1);assert.ok(calls.filter(c=>c.url.includes('/calendar/')).every(c=>c.method==='GET'));await integration.disconnect();assert.equal(state.items.length,0);assert.equal((await integration.status()).connected,false);}finally{globalThis.fetch=originalFetch;db.close();for(const key of ['GOOGLE_CLIENT_ID','GOOGLE_CLIENT_SECRET','GOOGLE_REDIRECT_URI']){if(old[key])process.env[key]=old[key];else delete process.env[key];}}
});
