import {randomBytes,createHash} from 'node:crypto';
const scope='https://www.googleapis.com/auth/calendar.readonly';
export function googleIntegration(db, readState, writeState) {
  db.exec('CREATE TABLE IF NOT EXISTS integrations (id TEXT PRIMARY KEY, data TEXT); CREATE TABLE IF NOT EXISTS oauth_states (nonce TEXT PRIMARY KEY, session TEXT, verifier TEXT, expires INTEGER)');
  const get=()=>JSON.parse(db.prepare("SELECT data FROM integrations WHERE id='google'").get()?.data||'{}');
  const set=v=>db.prepare("INSERT INTO integrations VALUES('google',?) ON CONFLICT(id) DO UPDATE SET data=excluded.data").run(JSON.stringify(v));
  const configured=()=>!!(process.env.GOOGLE_CLIENT_ID&&process.env.GOOGLE_CLIENT_SECRET&&process.env.GOOGLE_REDIRECT_URI);
  async function google(path,opts={}) {
    let stored=get();if(!stored.access_token)throw Object.assign(Error('Connect Google Calendar first.'),{status:400});
    if(Date.now()>stored.expires_at-60000){const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',body:new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID,client_secret:process.env.GOOGLE_CLIENT_SECRET,grant_type:'refresh_token',refresh_token:stored.refresh_token}),signal:AbortSignal.timeout(20000)});const data=await r.json();if(!r.ok)throw Error('Google authorization expired. Reconnect your account.');stored={...stored,...data,expires_at:Date.now()+data.expires_in*1000};set(stored);}
    const r=await fetch('https://www.googleapis.com/calendar/v3/'+path,{...opts,headers:{Authorization:'Bearer '+stored.access_token},signal:AbortSignal.timeout(20000)});
    if(!r.ok)throw Object.assign(Error('Google Calendar request failed.'),{status:502,googleStatus:r.status});return r.json();
  }
  return {
    status:()=>({configured:configured(),connected:!!get().access_token,selected:get().selected||[],lastSync:get().lastSync||null}),
    auth(session) {if(!configured())throw Object.assign(Error('Google Calendar requires server OAuth configuration.'),{status:503});const nonce=randomBytes(32).toString('hex'),verifier=randomBytes(32).toString('base64url');db.prepare('INSERT INTO oauth_states VALUES(?,?,?,?)').run(nonce,session,verifier,Date.now()+600000);const q=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID,redirect_uri:process.env.GOOGLE_REDIRECT_URI,response_type:'code',scope,access_type:'offline',prompt:'consent',state:nonce,code_challenge:createHash('sha256').update(verifier).digest('base64url'),code_challenge_method:'S256'});return {url:'https://accounts.google.com/o/oauth2/v2/auth?'+q};},
    async callback(code,nonce,session) {const row=db.prepare('SELECT * FROM oauth_states WHERE nonce=? AND session=? AND expires>?').get(nonce,session,Date.now());if(!row)throw Object.assign(Error('Expired or invalid authorization. Please connect again.'),{status:400});db.prepare('DELETE FROM oauth_states WHERE nonce=?').run(nonce);const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',body:new URLSearchParams({code,client_id:process.env.GOOGLE_CLIENT_ID,client_secret:process.env.GOOGLE_CLIENT_SECRET,redirect_uri:process.env.GOOGLE_REDIRECT_URI,grant_type:'authorization_code',code_verifier:row.verifier}),signal:AbortSignal.timeout(20000)});const data=await r.json();if(!r.ok)throw Error('Google authorization failed.');set({...data,expires_at:Date.now()+data.expires_in*1000,selected:[]});},
    async calendars(){let list=[],pageToken;do{const d=await google('users/me/calendarList?'+new URLSearchParams({maxResults:'250',...(pageToken?{pageToken}:{})}));list.push(...(d.items||[]).map(c=>({id:c.id,name:c.summary})));pageToken=d.nextPageToken;}while(pageToken);return list;},
    async sync(selected){const stored=get(),state=readState();if(!Array.isArray(selected)||selected.length>20)throw Error('Choose up to 20 calendars.');for(const entry of selected)if(!state.worlds.some(w=>w.id===entry.world))throw Error('Assign each calendar to a World.');const syncTokens={...stored.syncTokens},fullResets=new Set();let updates=[];
      for(const entry of selected){let pageToken,token=syncTokens[entry.id],attempt=0;if(!token)fullResets.add(entry.id);while(true){try{do{const params=new URLSearchParams({maxResults:'250',singleEvents:'true',showDeleted:'true',...(token?{syncToken:token}:{}),...(pageToken?{pageToken}:{})});const data=await google('calendars/'+encodeURIComponent(entry.id)+'/events?'+params);updates.push(...(data.items||[]).filter(e=>e.status==='cancelled'||e.start).map(e=>({id:'google-'+createHash('sha256').update(entry.id+e.id).digest('hex').slice(0,32),world:entry.world,type:'event',title:e.summary||'Untitled Google event',description:e.description||'',start_at:e.start?.dateTime||e.start?.date+'T00:00',end_at:e.end?.dateTime||e.end?.date,created_at:e.created||new Date().toISOString(),updated_at:e.updated,external:{provider:'Google Calendar',calendar:entry.id,event:e.id,url:e.htmlLink},cancelled:e.status==='cancelled'})));pageToken=data.nextPageToken;if(data.nextSyncToken)syncTokens[entry.id]=data.nextSyncToken;}while(pageToken);break;}catch(e){if(e.googleStatus===410&&attempt++===0){token=null;pageToken=null;fullResets.add(entry.id);updates=updates.filter(i=>i.external.calendar!==entry.id);continue}throw e;}}}
      // Apply all remote changes only after every selected calendar has fetched successfully.
      const latest=readState(),ids=new Set(selected.map(e=>e.id));latest.items=latest.items.filter(i=>!i.external||(ids.has(i.external.calendar)&&!fullResets.has(i.external.calendar)));for(const entry of selected)latest.items.filter(i=>i.external?.calendar===entry.id).forEach(i=>i.world=entry.world);for(const item of updates){latest.items=latest.items.filter(i=>i.id!==item.id);if(!item.cancelled){delete item.cancelled;latest.items.push(item)}}writeState(latest);set({...get(),selected,syncTokens,lastSync:new Date().toISOString()});return {count:updates.length};},
    async disconnect(){const stored=get();if(stored.access_token)await fetch('https://oauth2.googleapis.com/revoke',{method:'POST',body:new URLSearchParams({token:stored.refresh_token||stored.access_token}),signal:AbortSignal.timeout(10000)}).catch(()=>{});db.prepare("DELETE FROM integrations WHERE id='google'").run();const s=readState();s.items=s.items.filter(i=>!i.external);writeState(s);return {ok:true};}
  };
}
