import {test} from 'node:test';
import assert from 'node:assert/strict';
import {normalize,validateState,activeRocks,rockState,worldStatus,attention,reorder,promotionMessages} from '../public/domain.js';
const now=new Date('2026-09-20T12:00:00Z');
const base=()=>normalize({worlds:[{id:'w',name:'World',status:'on'}],items:[],captures:[]},now);
function rock(id,world='w',status='on'){return {id,world,type:'rock',title:id,description:'A measurable finished outcome',due_at:'2026-12-20',status,created_at:now.toISOString()};}
test('migration preserves records and relationships while removing vocabulary',()=>{const s=normalize({vocabulary:'Planet',worlds:[{id:'w',name:'Ongoing',purpose:'Enduring'}],items:[{id:'n',world:'inbox',type:'note',title:'Captured context',created:'2026-09-01'}],captures:[{text:'context'}],connections:[{from:'w',to:'old'}]},now);assert.equal(s.items.length,1);assert.equal(s.worlds.length,2);assert.equal(s.worlds[0].summary,'Enduring');assert.equal(s.items[0].world,'legacy-inbox');assert.equal(s.connections.length,1);assert.equal(s.vocabulary,undefined)});
test('only three Rocks activate per World and completion promotes queue',()=>{const before=base();before.items=['a','b','c','d'].map(x=>rock(x));assert.equal(rockState(before,before.items[3]),'Inactive');const after=structuredClone(before);after.items[0].completed_at=now.toISOString();assert.deepEqual(activeRocks(after,'w').map(i=>i.id),['b','c','d']);assert.match(promotionMessages(before,after)[0],/d is now Active/)});
test('deactivation promotes the next eligible queued Rock without deleting anything',()=>{const s=base();s.items=['a','b','c','d'].map(x=>rock(x));s.items[1].deactivated=true;assert.deepEqual(activeRocks(s,'w').map(i=>i.id),['a','c','d']);assert.equal(s.items.length,4)});
test('World status derives from majority, ties/no Rocks need review, override wins',()=>{const s=base(),w=s.worlds[0];assert.equal(worldStatus(s,w).status,'review');s.items=[rock('a'),rock('b','w','off')];assert.equal(worldStatus(s,w).status,'review');s.items.push(rock('c','w','off'));assert.equal(worldStatus(s,w).status,'off');w.status_override='on';assert.equal(worldStatus(s,w).status,'on')});
test('stale To-Dos survive normalization and rescheduling does not reset age',()=>{const s=base();s.items=[{id:'t',type:'todo',title:'Still matters',world:'w',created_at:'2026-09-01T12:00:00Z',due_at:'2026-12-01'}];const n=normalize(s,now);assert.equal(n.items.length,1);assert.equal(attention(n.items[0],now).level,'critical');assert.equal(attention(n.items[0],now).overdue,false);n.items[0].due_at='2026-09-19';assert.equal(attention(n.items[0],now).overdue,true)});
test('finished Rocks and To-Dos archive at seven days; unfinished and Projects do not',()=>{const s=base();s.items=[{...rock('r'),completed_at:'2026-09-13T12:00:00Z'},{id:'t',world:'w',type:'todo',title:'Open',created_at:'2026-01-01T12:00:00Z'}];s.projects=[{id:'p',world:'w',name:'Complete project',status:'completed'}];const n=normalize(s,now);assert.ok(n.items[0].archived_at);assert.ok(!n.items[1].archived_at);assert.ok(!n.projects[0].archived_at);assert.equal(normalize(n,now).audit.length,n.audit.length)});
test('immutable timestamps are server enforced',()=>{const s=base();s.items=[{id:'n',world:'w',type:'note',title:'Note',created_at:'2026-09-01T12:00:00Z',updated_at:'2026-09-01T12:00:00Z'}];const next=structuredClone(s);next.items[0].created_at=now.toISOString();const result=validateState(next,s,now);assert.equal(result.items[0].created_at,'2026-09-01T12:00:00Z')});
test('World cap excludes archived Worlds and rejects eleven active Worlds',()=>{const s=base(),n=structuredClone(s);n.worlds=Array.from({length:11},(_,x)=>({...s.worlds[0],id:'w'+x}));assert.throws(()=>validateState(n,s,now),/ten active Worlds/);n.worlds[10].archived_at=now.toISOString();assert.equal(validateState(n,s,now).worlds.length,11)});
test('Projects belong to one World and Rocks cannot belong to Projects',()=>{const s=base();s.projects=[{id:'p',name:'Project',world:'missing'}];assert.throws(()=>validateState(s,base(),now),/one World/);s.projects[0].world='w';s.items=[{...rock('r'),project:'p'}];assert.throws(()=>validateState(s,base(),now),/cannot belong to a Project/)});
test('checkpoint description/date and unique linked To-Do are required',()=>{const s=base();s.items=[rock('r'),{id:'cp',type:'todo',world:'w',rock:'r',checkpoint_id:'c',title:'Checkpoint',due_at:'2026-10-01'}];assert.throws(()=>validateState(s,base(),now),/description and date/);s.items[1].description='Review the outline';assert.equal(validateState(s,base(),now).items.length,2);s.items.push({...s.items[1],id:'duplicate'});assert.throws(()=>validateState(s,base(),now),/exactly one/)});
test('global and World priority orders remain independent',()=>{const s=base();s.items=['a','b','c'].map(id=>({id,type:'todo',world:'w',title:id}));reorder(s,'c',-1,'world:w');assert.deepEqual(s.orders['world:w'],['a','c','b']);assert.equal(s.orders.global,undefined);reorder(s,'b',-1,'global');assert.deepEqual(s.orders.global,['b','a','c']);assert.deepEqual(s.orders['world:w'],['a','c','b'])});
